In [9]:
import numpy as np

x = np.array([1,5,3,8])
print(x)

[1 5 3 8]


In [10]:
x_lista = [1,5,3,8]
print(x_lista)

[1, 5, 3, 8]


In [16]:
x_one = np.ones(10)
print(x_one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
x_zero = np.zeros(10)
print(x_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [30]:
x_one2 = np.ones([2,3])
print(x_one2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [28]:
x_zero2 = np.zeros([2,3])
print(x_zero2)

[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
print(np.arange(1,10,0.5))


[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [38]:
suma = x_one2 + x_zero2
print(suma)

suma2 = suma + x_one2
print(suma2)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]]


In [39]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.shape)
print(array.size)
print(array.ndim)

(2, 3)
6
2


In [45]:
array_reshape = array.reshape((3, 2))
print(array_reshape)

[[1 2]
 [3 4]
 [5 6]]


In [46]:
array_flatten = array.flatten()
print(array_flatten)

[1 2 3 4 5 6]


In [48]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

suma = array1 + array2
resta = array1 - array2

print("Suma:", suma)
print("Resta:", resta)


Suma: [5 7 9]
Resta: [-3 -3 -3]


In [49]:
multiplicacion = array1 * array2
division = array1 / array2

print("Multiplicación:", multiplicacion)
print("División:", division)

Multiplicación: [ 4 10 18]
División: [0.25 0.4  0.5 ]


In [53]:
array = np.array([1, 2, 3, 4, 5])
print(np.sum(array))  # Suma de todos los elementos
print(np.prod(array))  # Producto de todos los elementos
print(np.mean(array)) # Mediana o Promedio
print(np.median(array)) # Mediana o Promedio
print(np.std(array)) # Mediana o Promedio
print(np.var(array)) # Mediana o Promedio

15
120
3.0
3.0
1.4142135623730951
2.0


In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.sum(array, axis=0))  # Suma a lo largo de las columnas
print(np.sum(array, axis=1))  # Suma a lo largo de las filas